<a href="https://colab.research.google.com/github/popovycj/olx-rental-price-analysis/blob/main/olx_rental_analysis_project_cleaning_part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd

In [46]:
column_names = ['title', 'price', 'price_currency', 'description', 'views_count', 'created_at', 'options', 'location', 'region', 
                'seller_name', 'seller_registration_date', 'seller_link', 'announcement_link']

df = pd.read_csv('data.csv', names=column_names, header=None)

df.tail()

,title,price,price_currency,description,views_count,created_at,options,location,region,seller_name,seller_registration_date,seller_link,announcement_link
4917,2 х ком.метро Позняки 5 минут ул.Срибнокильская 8,7500.0,UAH,"Чистая,аккуратная,стиральная , кондиционеры.\n...",1100,21 травня 2023 р.,"['Бізнес', 'Поверх: 7', 'Поверховість: 16', 'З...","Київ, Дарницький",Київська область,Надежда,жовтень 2012,https://tmsk.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/2-h-kom-met...
4918,СВОЯ 2ком Деловая Тютюнника (Барбюса) Большая ...,28000.0,UAH,От собственника (без комиссии). Сдам 2ком. ква...,257,21 травня 2023 р.,"['Бізнес', 'Без комісії', 'Поверх: 7', 'Поверх...","Київ, Печерський",Київська область,Власник,травень 2015,https://www.olx.ua/d/uk/list/user/2fQZG/,https://www.olx.ua/d/uk/obyavlenie/svoya-2kom-...
4919,Здам 2 кк вул. Соборна 103/8,9500.0,UAH,"Здається 2 кк ЖК Європейка. Квартира простора,...",36,Сьогодні о 07:45,"['Бізнес', 'Поверх: 2', 'Поверховість: 6', 'За...",Софіївська Борщагівка,Київська область,Світлана,лютий 2008,https://www.olx.ua/d/uk/list/user/46Yv/,https://www.olx.ua/d/uk/obyavlenie/zdam-2-kk-v...
4920,None,None,None,None,None,None,None,None,Київська область,None,None,None,https://www.olx.ua/d/uk/obyavlenie/orenda-1k-k...
4921,2-х кімнатна квартира в центрі Борисполя зі св...,10000.0,UAH,2-кімнатна квартира в будинку на 2-му поверсі....,102,21 травня 2023 р.,"['Бізнес', 'Готовий співпрацювати з ріелторами...",Бориспіль,Київська область,Олексій,вересень 2019,https://www.olx.ua/d/uk/list/user/oyDCM/,https://www.olx.ua/d/uk/obyavlenie/2-h-kmnatna...

In [47]:
# Check uniqueness

df.drop_duplicates(subset=['announcement_link'], inplace=True)

len(df) == df['announcement_link'].nunique()

True

In [48]:
# Remove views_count column because of its unrepresentativeness and uselessness

df.drop('views_count', axis=1, inplace=True)

df.columns

Index(['title', 'price', 'price_currency', 'description', 'created_at',
       'options', 'location', 'region', 'seller_name',
       'seller_registration_date', 'seller_link', 'announcement_link'],
      dtype='object')

In [49]:
# Convert any other currencies to UAH

USD_to_UAH = 37.5
EUR_to_UAH = 40.5

df.loc[df['price_currency'] == 'USD', 'price'] = df[df['price_currency'] == 'USD']['price'].apply(lambda price: float(price) * USD_to_UAH)
df.loc[df['price_currency'] == 'EUR', 'price'] = df[df['price_currency'] == 'EUR']['price'].apply(lambda price: float(price) * EUR_to_UAH)

df[df['price_currency'] == 'EUR'].head()

,title,price,price_currency,description,created_at,options,location,region,seller_name,seller_registration_date,seller_link,announcement_link
295,Сдам квартиру в центре города,4657.5,EUR,Сдам квартиру на длительный период в центре го...,06 травня 2023 р.,"['Приватна особа', 'Тип будинку: Хрущовка', 'П...",Скадовськ,Херсонська область,Татьяна,травень 2017,https://www.olx.ua/d/uk/list/user/6Bq82/,https://www.olx.ua/d/uk/obyavlenie/sdam-kvarti...
692,Оренда вул.Пекарська Без комісії Торг ЦентрКлу...,34425.0,EUR,1.Від власника. Тому комісія-не потрібна.\nКва...,20 травня 2023 р.,"['Приватна особа', 'Без комісії', 'Тип будинку...","Львів, Галицький",Львівська область,vadimbashta,серпень 2020,https://www.olx.ua/d/uk/list/user/vEdxo/,https://www.olx.ua/d/uk/obyavlenie/orenda-vul-...
727,Оренда 2кім квартири 75 м кв + кухня-студіо но...,16200.0,EUR,Оренда 2кім ізольовані квартири 75 м кв + кухн...,Сьогодні о 12:04,"['Бізнес', 'Тип будинку: Житловий фонд від 201...","Львів, Залізничний",Львівська область,Лілія,грудень 2017,https://www.olx.ua/d/uk/list/user/8fWqY/,https://www.olx.ua/d/uk/obyavlenie/orenda-2km-...
787,"Оренда 2 кімнатної квартири Львів, Мечникова",20250.0,EUR,Оренда 2кім.кв. по вул.Мечникова.\nНОВОБУДОВА ...,Сьогодні о 10:32,"['Бізнес', 'Готовий співпрацювати з ріелторами...","Львів, Личаківський",Львівська область,Богдан,травень 2020,https://www.olx.ua/d/uk/list/user/w6L7A/,https://www.olx.ua/d/uk/obyavlenie/orenda-2-km...
1720,Апартаменти делюкс в Аркадіі,80595.0,EUR,"Ця світла, гарна та простора квартира знаходит...",19 травня 2023 р.,"['Приватна особа', 'Без комісії', 'Готовий спі...","Одеса, Приморський",Одеська область,Сергій,травень 2023,https://www.olx.ua/d/uk/list/user/1bDK0a/,https://www.olx.ua/d/uk/obyavlenie/apartamenti...

In [50]:
# Remove price_currency column

df.drop('price_currency', axis=1, inplace=True)

df.head()

,title,price,description,created_at,options,location,region,seller_name,seller_registration_date,seller_link,announcement_link
0,Здам в оренду 3 кімнатну квартиру район 10 мік...,7000.0,Здам в аренду 3 кімнатну квартиру район 10 мік...,19 травня 2023 р.,"['Бізнес', 'Тип будинку: Житловий фонд 91-2000...",Суми,Сумська область,Наталія,листопад 2016,https://visla.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/zdam-v-oren...
1,"Квартира, вул.СКД",3000.0,Місцерозташування: вулиця Холодноярської Брига...,15 травня 2023 р.,"['Бізнес', 'Тип будинку: Чешка', 'Поверх: 2', ...",Суми,Сумська область,Татьяна,жовтень 2017,https://www.olx.ua/d/uk/list/user/7SAvG/,https://www.olx.ua/d/uk/obyavlenie/kvartira-vu...
2,Сдам 1 к.кв. центр (Ильинская церковь ориентир),3200.0,Сдается однокомнатная квартира на 2 этаже в це...,11 травня 2023 р.,"['Бізнес', 'Поверх: 2', 'Поверховість: 5', 'За...",Суми,Сумська область,Анна,травень 2018,https://www.olx.ua/d/uk/list/user/cYVsc/,https://www.olx.ua/d/uk/obyavlenie/sdam-1-k-kv...
3,Здам 3к на вул. Харківській,7500.0,Здам в оренду 3к.квартиру на вул. Харківській\...,Сьогодні о 06:43,"['Бізнес', 'Поверх: 4', 'Поверховість: 9', 'За...",Суми,Сумська область,Яна,жовтень 2018,https://rielty-plaza.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/zdam-3k-na-...
4,Проспект Свободи оренда 1 кім квартиру,3200.0,Здам в оренду квартиру на Проспекті Свободи. (...,19 травня 2023 р.,"['Бізнес', 'Поверх: 3', 'Поверховість: 9', 'За...",Суми,Сумська область,Єлизавета,жовтень 2020,https://www.olx.ua/d/uk/list/user/yjn6T/,https://www.olx.ua/d/uk/obyavlenie/prospekt-sv...

In [51]:
# Remove blank announcements

df = df[df['price'] != 'None']

df.tail()

,title,price,description,created_at,options,location,region,seller_name,seller_registration_date,seller_link,announcement_link
4916,Сдам 2к квартиру по ул. Кошиця 7 метро Позняки...,9990.0,Сдам уютную 2к квартиру ул. Кошица 7 метро Ха...,21 травня 2023 р.,"['Бізнес', 'Поверх: 3', 'Поверховість: 9', 'За...","Київ, Дарницький",Київська область,Татьяна,червень 2017,https://www.olx.ua/d/uk/list/user/6OIqK/,https://www.olx.ua/d/uk/obyavlenie/sdam-2k-kva...
4917,2 х ком.метро Позняки 5 минут ул.Срибнокильская 8,7500.0,"Чистая,аккуратная,стиральная , кондиционеры.\n...",21 травня 2023 р.,"['Бізнес', 'Поверх: 7', 'Поверховість: 16', 'З...","Київ, Дарницький",Київська область,Надежда,жовтень 2012,https://tmsk.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/2-h-kom-met...
4918,СВОЯ 2ком Деловая Тютюнника (Барбюса) Большая ...,28000.0,От собственника (без комиссии). Сдам 2ком. ква...,21 травня 2023 р.,"['Бізнес', 'Без комісії', 'Поверх: 7', 'Поверх...","Київ, Печерський",Київська область,Власник,травень 2015,https://www.olx.ua/d/uk/list/user/2fQZG/,https://www.olx.ua/d/uk/obyavlenie/svoya-2kom-...
4919,Здам 2 кк вул. Соборна 103/8,9500.0,"Здається 2 кк ЖК Європейка. Квартира простора,...",Сьогодні о 07:45,"['Бізнес', 'Поверх: 2', 'Поверховість: 6', 'За...",Софіївська Борщагівка,Київська область,Світлана,лютий 2008,https://www.olx.ua/d/uk/list/user/46Yv/,https://www.olx.ua/d/uk/obyavlenie/zdam-2-kk-v...
4921,2-х кімнатна квартира в центрі Борисполя зі св...,10000.0,2-кімнатна квартира в будинку на 2-му поверсі....,21 травня 2023 р.,"['Бізнес', 'Готовий співпрацювати з ріелторами...",Бориспіль,Київська область,Олексій,вересень 2019,https://www.olx.ua/d/uk/list/user/oyDCM/,https://www.olx.ua/d/uk/obyavlenie/2-h-kmnatna...

In [54]:
from random import randint
import ast

def parse_options(str_options):
    single_keys = ['Тип', 'Додаткова інформація', 'Тип будинку',
                   'Поверх', 'Поверховість', 'Загальна площа', 'Площа кухні',
                   'Тип стін', 'Кількість кімнат', 'Планування', 'Cанвузол',
                   'Опалення', 'Ремонт', 'Меблювання']

    multiple_keys = ['Додаткова інформація', 'Домашні улюбленці', 'Побутова техніка',
                     'Мультимедіа', 'Комфорт', 'Комунікації', 'Інфраструктура (до 500 метрів)',
                     'Ландшафт (до 1 км.)', 'Додатково']

    options = {key: [] if key in multiple_keys else None for key in single_keys + multiple_keys}

    try:
        array_of_options = ast.literal_eval(str_options)
        if not isinstance(array_of_options, list):
            return options

        options['Тип'] = array_of_options.pop(0)

        while array_of_options and array_of_options[0] in ['Без комісії', 'Готовий співпрацювати з ріелторами', 'Для спільної оренди']:
            options['Додаткова інформація'].append(array_of_options.pop(0))

        for option in array_of_options:
            key, value = option.split(': ', 1)
            if key in ['Побутова техніка', 'Мультимедіа', 'Комфорт', 'Комунікації', 'Інфраструктура (до 500 метрів)', 'Ландшафт (до 1 км.)', 'Додатково']:
                value = value.split(', ')
            elif key == 'Домашні улюбленці':
                value = [x.strip(', ')[:-2] for x in value.split('Так, ') if len(x) > 1] if 'Ні' not in value else []
            else:
                value = value.replace('м²', '').replace('кімната', '').replace('кімнати', '').replace('кімнат', '').strip()
            options[key] = value
    except ValueError:
        pass

    return options


index = randint(1, 8000)
# index = 3352
print(f'INDEX: {index}')
options = df['options'][index]
print('-'*20 + 'NOT CLEARER' + '-'*20)
print(options)
print('-'*20 + 'CLEARER' + '-'*20)
print(parse_options(options))

INDEX: 2548
--------------------NOT CLEARER--------------------
['Приватна особа', 'Тип будинку: Житловий фонд 80-90-і', 'Поверх: 3', 'Поверховість: 5', 'Загальна площа: 50 м²', 'Площа кухні: 7 м²', 'Домашні улюбленці: Ні 🥺', 'Кількість кімнат: 2 кімнати', 'Cанвузол: Суміжний', 'Опалення: Централізоване', 'Ремонт: Житловий стан', 'Побутова техніка: Холодильник, Пральна машина']
--------------------CLEARER--------------------
{'Тип': 'Приватна особа', 'Додаткова інформація': [], 'Тип будинку': 'Житловий фонд 80-90-і', 'Поверх': '3', 'Поверховість': '5', 'Загальна площа': '50', 'Площа кухні': '7', 'Тип стін': None, 'Кількість кімнат': '2', 'Планування': None, 'Cанвузол': 'Суміжний', 'Опалення': 'Централізоване', 'Ремонт': 'Житловий стан', 'Меблювання': None, 'Домашні улюбленці': [], 'Побутова техніка': ['Холодильник', 'Пральна машина'], 'Мультимедіа': [], 'Комфорт': [], 'Комунікації': [], 'Інфраструктура (до 500 метрів)': [], 'Ландшафт (до 1 км.)': [], 'Додатково': []}

In [55]:
df_options = pd.concat([df['options'].apply(parse_options)], axis=1)
df_options

                                                options
0     {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
1     {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
2     {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
3     {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
4     {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
...                                                 ...
4916  {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
4917  {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
4918  {'Тип': 'Бізнес', 'Додаткова інформація': ['Бе...
4919  {'Тип': 'Бізнес', 'Додаткова інформація': [], ...
4921  {'Тип': 'Бізнес', 'Додаткова інформація': ['Го...

[4764 rows x 1 columns]

In [56]:
# Extract all options keys as new columns

df['options'] = df['options'].apply(parse_options)

for key in df['options'][0].keys():
    df[key] = df['options'].apply(lambda x: x[key])

df = df.drop('options', axis=1)

df.columns

Index(['title', 'price', 'description', 'created_at', 'location', 'region',
       'seller_name', 'seller_registration_date', 'seller_link',
       'announcement_link', 'Тип', 'Додаткова інформація', 'Тип будинку',
       'Поверх', 'Поверховість', 'Загальна площа', 'Площа кухні', 'Тип стін',
       'Кількість кімнат', 'Планування', 'Cанвузол', 'Опалення', 'Ремонт',
       'Меблювання', 'Домашні улюбленці', 'Побутова техніка', 'Мультимедіа',
       'Комфорт', 'Комунікації', 'Інфраструктура (до 500 метрів)',
       'Ландшафт (до 1 км.)', 'Додатково'],
      dtype='object')

In [57]:
# Convert all prices to float, remove invalid prices

df['price'] = pd.to_numeric(df['price'], errors='coerce')
df.dropna(subset=['price'], inplace=True)

df['price'].apply(lambda x: '{:.2f}'.format(x)).unique()

array(['7000.00', '3000.00', '3200.00', '7500.00', '2800.00', '11500.00',
       '4000.00', '3700.00', '1800.00', '2600.00', '400000.00', '1500.00',
       '2500.00', '1300.00', '10000.00', '4500.00', '8000.00', '3500.00',
       '2000.00', '5000.00', '1200.00', '3600.00', '2300.00', '2200.00',
       '9000.00', '3800.00', '4300.00', '14000.00', '4700.00', '6000.00',
       '4200.00', '13000.00', '15000.00', '5500.00', '2400.00', '2700.00',
       '1000.00', '6500.00', '1900.00', '1400.00', '3400.00', '1700.00',
       '12000.00', '5625.00', '13125.00', '4725.00', '16125.00',
       '30000.00', '20000.00', '24375.00', '12500.00', '4657.50',
       '8500.00', '2999.00', '2900.00', '9500.00', '9375.00', '6750.00',
       '3950.00', '16000.00', '375000.00', '18000.00', '800.00',
       '10700.00', '11000.00', '4999.00', '17000.00', '28125.00',
       '18500.00', '20625.00', '18712.50', '18750.00', '26250.00',
       '22500.00', '19000.00', '19125.00', '14500.00', '16875.00',
       '23000.00', '8300.00', '33750.00', '9900.00', '13800.00',
       '12900.00', '45000.00', '16500.00', '6200.00', '41250.00',
       '26212.50', '37500.00', '200.00', '31875.00', '15999.00',
       '34425.00', '67500.00', '16200.00', '13500.00', '35625.00',
       '12750.00', '75000.00', '26000.00', '8200.00', '20250.00',
       '17250.00', '19500.00', '63750.00', '18999.00', '6800.00',
       '5800.00', '10500.00', '5999.00', '5300.00', '3990.00', '4800.00',
       '7800.00', '9999.00', '7999.00', '3250.00', '6999.00', '27000.00',
       '7200.00', '25000.00', '1350000.00', '11800.00', '1537500.00',
       '3900.00', '6700.00', '8700.00', '5900.00', '13087.50', '8250.00',
       '11999.00', '48750.00', '11250.00', '8970.00', '3300.00',
       '5499.00', '12499.00', '1450.00', '5600.00', '80595.00', '9200.00',
       '5950.00', '7990.00', '15990.00', '6900.00', '52500.00',
       '22425.00', '32400.00', '50625.00', '13875.00', '12375.00',
       '3750.00', '12937.50', '11400.00', '15750.00', '18700.00',
       '60000.00', '24300.00', '14250.00', '108750.00', '21750.00',
       '202500.00', '9562.50', '10125.00', '9720.00', '7875.00',
       '8625.00', '8910.00', '8962.50', '7499.00', '10900.00', '10800.00',
       '4125.00', '9750.00', '6300.00', '18225.00', '32000.00', '7300.00',
       '25500.00', '7150.00', '17500.00', '11212.50', '10200.00',
       '8999.00', '283500.00', '14985.00', '9950.00', '24000.00',
       '21000.00', '15500.00', '13400.00', '5200.00', '12150.00',
       '20999.00', '6599.00', '28999.00', '324000.00', '22000.00',
       '3999.00', '13799.00', '14999.00', '6075.00', '18991.00',
       '29000.00', '10699.00', '8800.00', '20500.00', '7900.00',
       '17400.00', '35000.00', '28000.00', '13900.00', '4499.00',
       '7462.50', '8600.00', '6562.50', '162000.00', '22462.50',
       '5812.50', '17625.00', '14134.50', '14962.50', '14062.50',
       '12300.00', '6937.50', '7125.00', '8100.00', '48600.00',
       '93750.00', '13999.00', '180000.00', '141750.00', '17999.00',
       '7699.00', '56250.00', '9990.00', '7700.00', '15700.00',
       '18900.00', '12999.00', '2330.00', '14900.00', '9315.00',
       '16687.50', '11900.00', '1990.00', '5990.00', '112500.00',
       '5490.00', '3790.00', '6990.00', '21500.00', '14499.00',
       '11991.00', '16800.00', '17990.00', '16499.00', '10999.00',
       '9550.00', '19999.00', '105000.00', '59000.00', '82500.00',
       '31000.00', '150000.00', '4950.00', '43000.00', '33000.00',
       '9300.00', '9800.00', '4750.00', '17700.00', '16300.00',
       '131250.00'], dtype=object)

In [58]:
df = df[df['price'] <= 1_000_000]

df.nlargest(15, 'price')

,title,price,description,created_at,location,region,seller_name,seller_registration_date,seller_link,announcement_link,...,Ремонт,Меблювання,Домашні улюбленці,Побутова техніка,Мультимедіа,Комфорт,Комунікації,Інфраструктура (до 500 метрів),Ландшафт (до 1 км.),Додатково
15,Однокомнатная квартира,400000.0,Продам однокомнатную квартиру с ремонтом. Пров...,19 травня 2023 р.,Шостка,Сумська область,Людмила,травень 2023,https://www.olx.ua/d/uk/list/user/1bIFbK/,https://www.olx.ua/d/uk/obyavlenie/odnokomnatn...,...,Євроремонт,Без меблів,[],[Без побутової техніки],[Wi-Fi],"[Балкон, лоджія, Ванна]","[Центральна каналізація, Електрика, Вивіз відх...",[],[],[]
439,Продажа Центр! 2х к.кв./3эт. Академическая 59....,375000.0,Центр. Продажа 2х ком.квартиры 54.3 кв.м. 3й э...,20 травня 2023 р.,Краматорськ,Донецька область,Леся,листопад 2020,https://www.olx.ua/d/uk/list/user/zoIjp/,https://www.olx.ua/d/uk/obyavlenie/prodazha-ts...,...,None,None,[],[],[],[],[],[],[],[]
2703,Оренда квартири буковинська,324000.0,Здається 1 кімнатна дворівнева квартира вул. Б...,19 травня 2023 р.,Рівне,Рівненська область,Марія АН Срібна Карта,червень 2021,https://www.olx.ua/d/uk/list/user/HGN90/,https://www.olx.ua/d/uk/obyavlenie/orenda-kvar...,...,None,None,[],[],[],[],[],[],[],[]
2478,"оренда 1 к, центр, по вул. Короля Данила",283500.0,"здається в оренду однокімнатна квартира, на др...",20 травня 2023 р.,Івано-Франківськ,Івано-Франківська область,0935498488,серпень 2021,https://www.olx.ua/d/uk/list/user/JFxHd/,https://www.olx.ua/d/uk/obyavlenie/orenda-1-k-...,...,None,None,"[котик, маленький песик(до 10 кг)]","[Холодильник, Плита, Пральна машина]",[],"[Балкон, лоджія]",[],"[Центр міста, Аптека, Дитячий садок, Ринок, Па...",[Озеро],[Можна іноземцям]
1963,Здам в оренду квартиру,202500.0,"Двокімнатна квартира, є умови для проживання. ...",19 травня 2023 р.,Берегове,Закарпатська область,Ванесса,квітень 2020,https://www.olx.ua/d/uk/list/user/tpMPQ/,https://www.olx.ua/d/uk/obyavlenie/zdam-v-oren...,...,None,З меблями,[],"[Електрочайник, Плита, Холодильник, Пральна ма...","[Wi-Fi, Телевізор, Кабельне, цифрове ТБ]","[Ванна, Балкон, лоджія]","[Газ, Електрика, Центральна каналізація]","[Дитячий садок, Зупинка транспорту, Магазин, к...",[],[]
3482,Сдаю 1к квартиру-студию с гаражом,202500.0,Аренда 1к квартиры-студии с гаражом.Отдельное ...,21 травня 2023 р.,"Миколаїв, Заводський",Миколаївська область,Александр,червень 2021,https://www.olx.ua/d/uk/list/user/Hpibf/,https://www.olx.ua/d/uk/obyavlenie/sdayu-1k-kv...,...,Євроремонт,З меблями,[],"[Плита, Духова шафа, Мікрохвильова піч, Холоди...","[Wi-Fi, Швидкісний інтернет, Телевізор]","[Душова кабіна, Меблі на кухні, Гараж]","[Газ, Центральний водопровід, Електрика, Центр...","[Дитячий садок, Школа, Зупинка транспорту, Рин...",[],[]
3491,Здається двокімнатна квартира в центрі міста,180000.0,Двокімнатна квартира в центрі міста.\nПральна ...,19 травня 2023 р.,"Миколаїв, Заводський",Миколаївська область,Ekaterina,вересень 2022,https://www.olx.ua/d/uk/list/user/10hB6s/,https://www.olx.ua/d/uk/obyavlenie/zdatsya-dvo...,...,None,З меблями,[],"[Плита, Мікрохвильова піч, Холодильник, Пральн...",[],[],[],[],[],[]
3256,Здаю однокімнатну квартиру.,162000.0,"Здаю однокімнатну квартиру, старий фонд, божен...",19 травня 2023 р.,Чернівці,Чернівецька область,380953345108,травень 2023,https://www.olx.ua/d/uk/list/user/1bJ0El/,https://www.olx.ua/d/uk/obyavlenie/zdayu-odnok...,...,None,None,[],"[Холодильник, Варильна панель, Плита, Пральна ...",[Wi-Fi],"[Меблі на кухні, Душова кабіна]","[Газ, Центральний водопровід]","[Відділення банку, банкомат, Кінотеатр, театр,...",[],[]
4772,"Аренда 4к квартиры, ул. Саперное Поле, Печерск",150000.0,"Аренда 4к квартиры, ул. Саперное Поле, Печерск...",21 травня 2023 р.,"Київ, Печерський",Київська область,THE CAPITAL,березень 2021,https://capitalrent.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/arenda-4k-k...,...,Авторський проект,З меблями,[],"[Кавомашина, Електрочайник, Фен, Варильна пане...",[],[],[],[],[],[]
3492,Аренда 1 квартира на ул Космонавтов,141750.0,"Аренда 1 кв на Космонавтов ост.""Рассвет""Кварти...",18 травня 2023 р.,"Миколаїв, Iнгульський",Миколаївська область,Людмила,березень 2016,https://www.olx.ua/d/uk/list/user/33hUk/,https://www.olx.ua/d/uk/obyavlenie/arenda-1-kv...,...,Житловий стан,None,[],"[Холодильник, Пральна машина]",[],[],[],[],[],[]
4878,"Аренда 4к квартиры, Городецкого Архитектора ул...",131250.0,"Аренда 4к квартиры в Киеве, Печерский р-н, Гор...",21 травня 2023 р.,"Київ, Печерський",Київська область,АН All Star,жовтень 2018,https://www.olx.ua/d/uk/list/user/i146I/,https://www.olx.ua/d/uk/obyavlenie/arenda-4k-k...,...,None,None,[],[],[],[],[],[],[],[]
4360,"Оренда 2кімн.кварти,вул.Любецька",112500.0,Довгострокова аренда 2кімн.квартири по вул.Люб...,26 квітня 2023 р.,Чернігів,Чернігівська область,Олеся,жовтень 2018,https://kvadratmetr.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/orenda-2kmn...,...,Житловий стан,З меблями,[],"[Холодильник, Плита]",[],[],[],"[Відділення банку, банкомат, Аптека, Ринок, Ві...",[],[]
4867,Здається 4-кімнатна квартира в центрі з видом ...,112500.0,Ціну знижено! Здається в оренду квартира в сам...,21 травня 2023 р.,"Київ, Шевченківський",Київська область,Алена,березень 2018,https://www.olx.ua/d/uk/list/user/aEALu/,https://www.olx.ua/d/uk/obyavlenie/zdatsya-4-k...,...,Авторський проект,З меблями,"[великий песик, котик, середній песик(до 25 кг...","[Посудомийна машина, Холодильник, Варильна пан...","[Швидкісний інтернет, Телевізор, Wi-Fi]","[Балкон, лоджія, Ванна, Ліфт, Гостьовий паркін...","[Асфальтована дорога, Центральна каналізація, ...","[Відділення банку, банкомат, Кінотеатр, театр,...","[Пагорби, Парк, Річка]","[Можна іноземцям, Можна студентам, Можна з діт..."
1914,4-х комн. ЖК Busov Hill Бусловская 12 видовая!...,108750.0,Без комиссии! \n\nПредлагается в аренду видова...,20 травня 2023 р.,Мукачеве,Закарпатська область,Анна,травень 2015,https://www.olx.ua/d/uk/list/user/2fMMM/,https://www.olx.ua/d/uk/obyavlenie/4-h-komn-zh...,...,Авторський проект,З меблями,[],"[Праска, Фен, Сушильна машина, Пилосос, Мульти...","[Wi-Fi, Телевізор, Кабельне, цифрове ТБ, Швидк...","[Підігрів підлоги, Відеоспостереження, Сигналі...",[],[],"[Річка, Парк]",[]
4720,Без%Аренда!Центр!В.Васильківська46!3уровневая ...,105000.0,"Без%\nУнікальна ,Видова 3поверхова квартира (2...",21 травня 2023 р.,"Київ, Солом'янський",Київська область,Татьяна,травень 2012,https://masterplace.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/bez-arenda-...,...,Авторський проект,З меблями,[середній песик(до 25 кг)],"[Сушильна машина, Електрочайник, Холодильник, ...","[Кабельне, цифрове ТБ, Супутникове ТБ, Швидкіс...","[Відеоспостереження, Ліфт]","[Асфальтована дорога, Центральна каналізація, ...","[Відділення банку, банкомат, Автовокзал, Кінот...",[],[]

In [59]:
df = df[df['price'] >= 1_500]

df.nsmallest(15, 'price')

,title,price,description,created_at,location,region,seller_name,seller_registration_date,seller_link,announcement_link,...,Ремонт,Меблювання,Домашні улюбленці,Побутова техніка,Мультимедіа,Комфорт,Комунікації,Інфраструктура (до 500 метрів),Ландшафт (до 1 км.),Додатково
17,Сдам 1 ком квартиру в аренду в центре на длите...,1500.0,Сдаю 1 комнатную квартиру в центре на длительн...,16 травня 2023 р.,Конотоп,Сумська область,wigwamchik,травень 2023,https://www.olx.ua/d/uk/list/user/1aYVOF/,https://www.olx.ua/d/uk/obyavlenie/sdam-1-kom-...,...,Косметичний ремонт,З меблями,[],[Холодильник],"[Телевізор, Кабельне, цифрове ТБ]",[],"[Газ, Електрика, Вивіз відходів]",[],[Парк],[]
32,Сдаётся 1-х квартира ул. Холодногорская,1500.0,"Хороший косметический ремонт,в хороших условия...",11 травня 2023 р.,Суми,Сумська область,Ксения,лютий 2022,https://www.olx.ua/d/uk/list/user/RrCPV/,https://www.olx.ua/d/uk/obyavlenie/sdaetsya-1-...,...,None,З меблями,[],"[Холодильник, Пральна машина]","[Швидкісний інтернет, Телевізор]","[Ванна, Меблі на кухні]",[],"[Центр міста, Ринок, Зупинка транспорту]",[],[]
64,Здаєтьcя однокімнатна квартира по вулиці Засу...,1500.0,Здам 1 квартиру у центрі. \nВулиця Засумська р...,18 травня 2023 р.,Суми,Сумська область,Богдан,жовтень 2020,https://www.olx.ua/d/uk/list/user/yjn6T/,https://www.olx.ua/d/uk/obyavlenie/zdatcya-odn...,...,Косметичний ремонт,З меблями,[],[],"[Wi-Fi, Швидкісний інтернет, Телевізор]",[],[],[],[],[]
89,Сдам 1 ком квартиру на Труда (Хворостянка) без...,1500.0,"Сдам 1 ком квартиру , кiмната 18м, не кутова, ...",18 травня 2023 р.,Суми,Сумська область,Оксана Александровна,липень 2017,https://www.olx.ua/d/uk/list/user/79Lr4/,https://www.olx.ua/d/uk/obyavlenie/sdam-1-kom-...,...,Косметичний ремонт,None,[],[],[],[],[],[],[],[]
123,Здам кімнатну в гуртожитку як 1к.кв,1500.0,Здам! Кімнату 18м в гуртожитку Римського-Корса...,12 травня 2023 р.,Суми,Сумська область,Taтьяна,вересень 2018,https://www.olx.ua/d/uk/list/user/hnIb3/,https://www.olx.ua/d/uk/obyavlenie/zdam-kmnatn...,...,Косметичний ремонт,З меблями,[],"[Холодильник, Пральна машина]",[],[],[],[],[],[]
175,Однокомнатная квартира ул.Депутатская 12 г.Шо...,1500.0,Сдается\n\n1 комнатная квартира на первом этаж...,15 травня 2023 р.,Шостка,Сумська область,Виталий,травень 2014,https://www.olx.ua/d/uk/list/user/1F293/,https://www.olx.ua/d/uk/obyavlenie/odnokomnatn...,...,Житловий стан,З меблями,[],"[Холодильник, Плита]",[],[],[],"[Школа, Магазин, кіоск, Зупинка транспорту]",[],[]
182,Оренда 1к НА ПРОКОФ‘ЄВА ЛИШЕ ЗА 1500/міс!!,1500.0,НАЙДЕШЕВША ОРЕНДА гарної 1к в улюбленому район...,17 травня 2023 р.,Суми,Сумська область,Андрей,липень 2022,https://www.olx.ua/d/uk/list/user/X9ekb/,https://www.olx.ua/d/uk/obyavlenie/orenda-1k-n...,...,Житловий стан,None,[],[],[],[],[],[],[],"[Можна іноземцям, Можна курити, Можна студента..."
201,Супруна центр однокімнатна квартира. 1500,1500.0,Здається в оренду 1 кімнатна квартира центрі ....,10 травня 2023 р.,Суми,Сумська область,Оренда,жовтень 2020,https://www.olx.ua/d/uk/list/user/yjn6T/,https://www.olx.ua/d/uk/obyavlenie/supruna-tse...,...,Косметичний ремонт,З меблями,[маленький песик(до 10 кг)],[],[],[],[],[],[],[]
209,З технікою і меблями,1500.0,"Здається кімната в гуртожитку, Хіммістечко.\n\...",13 травня 2023 р.,Суми,Сумська область,Татьяна,жовтень 2017,https://www.olx.ua/d/uk/list/user/7SAvG/,https://www.olx.ua/d/uk/obyavlenie/z-tehnkoyu-...,...,Косметичний ремонт,З меблями,[],"[Холодильник, Мікрохвильова піч, Плита, Пральн...","[Кабельне, цифрове ТБ, Швидкісний інтернет, Те...",[Меблі на кухні],[],"[Дитячий садок, Школа, Зупинка транспорту]",[],[Можна з дітьми]
231,Здам 1 кімнатну квартиру по вулиці Лебединська...,1500.0,В квартирі є все для комфортного проживання:\n...,16 травня 2023 р.,Суми,Сумська область,Роман,вересень 2017,https://realty.olx.ua/uk,https://www.olx.ua/d/uk/obyavlenie/zdam-1-kmna...,...,Косметичний ремонт,З меблями,[],"[Холодильник, Плита]",[],"[Ванна, Гостьовий паркінг, Меблі на кухні]","[Асфальтована дорога, Центральна каналізація, ...","[Відділення банку, банкомат, Аптека, Лікарня, ...",[Парк],[]
856,Здаеться койкоместо для парней,1500.0,В3х комнатной квартире здаються койко места то...,17 травня 2023 р.,"Житомир, Сенний ринок",Житомирська область,Татьяна,лютий 2023,https://www.olx.ua/d/uk/list/user/17oFbI/,https://www.olx.ua/d/uk/obyavlenie/zdaetsya-ko...,...,Житловий стан,None,[],"[Плита, Мікрохвильова піч, Холодильник]","[Wi-Fi, Телевізор, Кабельне, цифрове ТБ]","[Ванна, Меблі на кухні, Гардероб, Балкон, лоджія]","[Газ, Електрика, Каналізація септик, Вивіз від...","[Зупинка транспорту, Ринок, Магазин, кіоск, Су...","[Річка, Ліс]",[]
865,Сдам 1 комнатную квартиру,1500.0,Сдам 1 комнатную квартиру в Коростене. Есть ме...,19 травня 2023 р.,Коростень,Житомирська область,Олег,червень 2021,https://www.olx.ua/d/uk/list/user/HNW2z/,https://www.olx.ua/d/uk/obyavlenie/sdam-1-komn...,...,None,None,[],[],[],[],[],[],[],[]
1146,Оренда приміщення в центрі,1500.0,"Оренда приміщення. Центр міста, біля світлофор...",30 квітня 2023 р.,Гайворон,Кіровоградська область,Михаил,березень 2008,https://www.olx.ua/d/uk/list/user/4rgi/,https://www.olx.ua/d/uk/obyavlenie/orenda-prim...,...,Євроремонт,З меблями,[],[],[],[Ванна],"[Центральна каналізація, Скважина]",[],[],[]
1188,Сдам 2 -ком.кв. в общежитии,1500.0,"С 18.05 сдается квартира в общежитии, только с...",10 травня 2023 р.,Олександрія,Кіровоградська область,оксана,серпень 2014,https://www.olx.ua/d/uk/list/user/1Nw7j/,https://www.olx.ua/d/uk/obyavlenie/sdam-2-kom-...,...,Житловий стан,Без меблів,[],"[Без побутової техніки, Плита]","[Кабельне, цифрове ТБ]",[Ліфт],[Електрика],"[Аптека, Дитячий садок, Дитячий майданчик, Шко...",[],[Тільки сім'ям]
1223,Здам квартиру недорого,1500.0,Здам квартиру недорого в Гайвороні в центрі бі...,Сьогодні о 07:19,Гайворон,Кіровоградська область,svitlanazotova4,листопад 2021,https://www.olx.ua/d/uk/list/user/NeWzf/,https://www.olx.ua/d/uk/obyavlenie/zdam-kvarti...,...,Косметичний ремонт,З меблями,[інша тваринка],[Електрочайник],[Без мультимедіа],[],[],"[Дитячий садок, Школа, Магазин, кіоск, Дитячий...",[],[]

In [60]:
df.columns

Index(['title', 'price', 'description', 'created_at', 'location', 'region',
       'seller_name', 'seller_registration_date', 'seller_link',
       'announcement_link', 'Тип', 'Додаткова інформація', 'Тип будинку',
       'Поверх', 'Поверховість', 'Загальна площа', 'Площа кухні', 'Тип стін',
       'Кількість кімнат', 'Планування', 'Cанвузол', 'Опалення', 'Ремонт',
       'Меблювання', 'Домашні улюбленці', 'Побутова техніка', 'Мультимедіа',
       'Комфорт', 'Комунікації', 'Інфраструктура (до 500 метрів)',
       'Ландшафт (до 1 км.)', 'Додатково'],
      dtype='object')

In [61]:
df = df[~df['region'].isin(['Крим (АРК)', 'Луганська область'])]

df.groupby('region').count()

,title,price,description,created_at,location,seller_name,seller_registration_date,seller_link,announcement_link,Тип,...,Ремонт,Меблювання,Домашні улюбленці,Побутова техніка,Мультимедіа,Комфорт,Комунікації,Інфраструктура (до 500 метрів),Ландшафт (до 1 км.),Додатково
region,,,,,,,,,,,,,,,,,,,,,
Івано-Франківська область,229,229,229,229,229,229,229,229,229,229,...,182,191,229,229,229,229,229,229,229,229
Волинська область,192,192,192,192,192,192,192,192,192,192,...,135,145,192,192,192,192,192,192,192,192
Вінницька область,196,196,196,196,196,196,196,196,196,196,...,150,158,196,196,196,196,196,196,196,196
Дніпропетровська область,218,218,218,218,218,218,218,218,218,218,...,150,175,218,218,218,218,218,218,218,218
Донецька область,204,204,204,204,204,204,204,204,204,204,...,91,141,204,204,204,204,204,204,204,204
Житомирська область,233,233,233,233,233,233,233,233,233,233,...,176,175,233,233,233,233,233,233,233,233
Закарпатська область,204,204,204,204,204,204,204,204,204,204,...,154,183,204,204,204,204,204,204,204,204
Запорізька область,191,191,191,191,191,191,191,191,191,191,...,126,131,191,191,191,191,191,191,191,191
Київська область,184,184,184,184,184,184,184,184,184,184,...,141,160,184,184,184,184,184,184,184,184
Кіровоградська область,235,235,235,235,235,235,235,235,235,235,...,153,186,235,235,235,235,235,235,235,235
Львівська область,234,234,234,234,234,234,234,234,234,234,...,189,203,234,234,234,234,234,234,234,234
Миколаївська область,199,199,199,199,199,199,199,199,199,199,...,151,173,199,199,199,199,199,199,199,199
Одеська область,195,195,195,195,195,195,195,195,195,195,...,153,160,195,195,195,195,195,195,195,195
Полтавська область,199,199,199,199,199,199,199,199,199,199,...,122,137,199,199,199,199,199,199,199,199
Рівненська область,200,200,200,200,200,200,200,200,200,200,...,152,179,200,200,200,200,200,200,200,200
Сумська область,236,236,236,236,236,236,236,236,236,236,...,189,202,236,236,236,236,236,236,236,236
Тернопільська область,203,203,203,203,203,203,203,203,203,203,...,189,157,203,203,203,203,203,203,203,203
Харківська область,237,237,237,237,237,237,237,237,237,237,...,163,181,237,237,237,237,237,237,237,237
Херсонська область,116,116,116,116,116,116,116,116,116,116,...,91,99,116,116,116,116,116,116,116,116
Хмельницька область,211,211,211,211,211,211,211,211,211,211,...,194,190,211,211,211,211,211,211,211,211
Черкаська область,191,191,191,191,191,191,191,191,191,191,...,143,162,191,191,191,191,191,191,191,191
Чернівецька область,199,199,199,199,199,199,199,199,199,199,...,146,182,199,199,199,199,199,199,199,199
Чернігівська область,206,206,206,206,206,206,206,206,206,206,...,131,155,206,206,206,206,206,206,206,206

In [62]:
df.to_csv('cleaned_data.csv', index=False)